# Created by trellis-cli vcanary
# Documentation: https://roots.io/trellis/docs/wordpress-sites/

wordpress_sites:
  tourmacapa.com.br:
    site_hosts:
    - canonical: staging.tourmacapa.com.br
      # redirects:
      # - www.staging.tourmacapa.com.br
    local_path: ../site
    branch: master
    repo: git@github.com:dsemblano/tourmacapa.git
    repo_subtree_path: site
    multisite:
      enabled: false
    ssl:
      enabled: true
      provider: letsencrypt
    cache:
      enabled: false
